apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: twenty-daily-backup
  namespace: twenty
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: twenty-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
