apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: twenty-server
  namespace: twenty
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: twenty
      app.kubernetes.io/component: server
