apiVersion: v1
kind: ConfigMap
metadata:
  name: twenty-keydb-config
  namespace: twenty
data:
  keydb.conf: |
    server-threads 4
    active-replica yes
    multi-master yes
    repl-backlog-size 64mb
    maxmemory-policy noeviction
    save 900 1 300 10
    appendonly yes
    appendfsync everysec
    hz 25
    tcp-keepalive 60
    timeout 0
